document.write(&quot;<meta content='Tutorila Linking' name='DC.Title'/>&quot;);
document.write(&quot;<meta content='Diesardiesa' name='DC.Creator'/>&quot;);
document.write(&quot;<meta content='text\/html' name='DC.Format' scheme='IMT'/>&quot;);
document.write(&quot;<meta content='Tutorial Linking' name='DC.Subject' scheme='MESH'/>&quot;);
document.write(&quot;<meta content='Diesardiesa' name='DC.Publisher'/>&quot;);
document.write(&quot;<meta content='http:\/\/tutoriallinking.blogspot.com' name='DC.Identifier'/>&quot;);
document.write(&quot;<meta content='diesardiesa@engineer.com' name='DC.creator.address'/> &quot;);
document.write(&quot;<meta content='id; INDONESIA' name='DC.Language' scheme='RFC1766'/>&quot;);
document.write(&quot;<meta content='17 Mei 2015' name='DC.Date'/>&quot;);
document.write(&quot;<meta content='17 Mei 2015' name='DC.Date.Modified'/>&quot;);
document.write(&quot;<meta content='Pintar itu Mahal Ayo kita Belajar - Jangan pernah malu bertanya, Malu bertanya sesat dijalan !' name='DC.Description'/>&quot;);
document.write(&quot;<meta content='text' name='DC.Type' scheme='DCMIType'/>&quot;);
document.write(&quot;<meta content='ISI DENGAN LINK PRIVACY POLICY ANDA' name='DC.Rights'/>&quot;);
document.write(&quot;<meta content='upkhcHdeKym2bffS4CIVhwGcJYKjII8iBxx4KnzNuo8' name='google-site-verification'/>&quot;);
document.write(&quot;<meta content='E08B02400E2E11CAA13AA89D9B7E1CAD' name='msvalidate.01'/>&quot;);
document.write(&quot;<meta content='zxy_Kpm0QpkPBkWB_YmrQE9YbUo' name='alexaVerifyID'/>&quot;);
document.write(&quot;<meta content='Indonesia' name='geo.placename'/>&quot;);
document.write(&quot;<meta content='diesardiesa' name='Author'/>&quot;);
document.write(&quot;<meta content='general' name='rating'/>&quot;);
document.write(&quot;<meta content='id' name='geo.country'/>&quot;);
document.write(&quot;<meta content='diesardiesa' property='fb:app_id'/>&quot;);
document.write(&quot;<meta content='diesardiesa' property='fb:admins'/>&quot;);
